# Generated by Django 5.2.1 on 2025-06-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_about_customuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='about',
            field=models.CharField(default='', max_length=255),
        ),
    ]
